/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import javax.swing.ImageIcon;

/**
 *
 * @author MASB
 */
public class Fportada extends javax.swing.JFrame {

    /**
     * Creates new form Fportada
     */
    public Fportada() {
        initComponents();
        this.setLocationRelativeTo(null);
        setIconImage(new ImageIcon(getClass().getResource("../IMAGENES/icono.jpeg")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        LOGOUpiicsa = new javax.swing.JLabel();
        LOGO = new javax.swing.JLabel();
        NOMBRE2 = new javax.swing.JLabel();
        NOMBRE = new javax.swing.JLabel();
        INTEGRANTES2 = new javax.swing.JLabel();
        NOMBRE1 = new javax.swing.JLabel();
        NOMBRE3 = new javax.swing.JLabel();
        NOMBRE4 = new javax.swing.JLabel();
        EQUIPO2 = new javax.swing.JLabel();
        NOMBRE5 = new javax.swing.JLabel();
        CONTINUAR1 = new javax.swing.JButton();
        FONDO = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LOGOUpiicsa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/Upiicasa.png"))); // NOI18N
        jPanel1.add(LOGOUpiicsa, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 30, -1, -1));

        LOGO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/LOGO.png"))); // NOI18N
        jPanel1.add(LOGO, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 270, -1));

        NOMBRE2.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        NOMBRE2.setText("Benitez Mejorado Diego ");
        jPanel1.add(NOMBRE2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 270, -1, 20));

        NOMBRE.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        NOMBRE.setForeground(new java.awt.Color(153, 153, 153));
        NOMBRE.setText("SECUENCIA  3CM40 ");
        jPanel1.add(NOMBRE, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 480, -1, 20));

        INTEGRANTES2.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        INTEGRANTES2.setForeground(new java.awt.Color(204, 204, 204));
        INTEGRANTES2.setText("INTEGRANTES ");
        jPanel1.add(INTEGRANTES2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 220, -1, 20));

        NOMBRE1.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        NOMBRE1.setText("Hurtado Razo Ashily Romina ");
        jPanel1.add(NOMBRE1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 310, -1, 20));

        NOMBRE3.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        NOMBRE3.setText("Flores Loyola Alan De Jesus ");
        jPanel1.add(NOMBRE3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 350, -1, 20));

        NOMBRE4.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        NOMBRE4.setText("Morales Lopez Luis Daniel ");
        jPanel1.add(NOMBRE4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 390, -1, 20));

        EQUIPO2.setFont(new java.awt.Font("Agency FB", 1, 48)); // NOI18N
        EQUIPO2.setForeground(new java.awt.Color(153, 153, 153));
        EQUIPO2.setText("E Q U I P O   02 ");
        jPanel1.add(EQUIPO2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, -1, 40));

        NOMBRE5.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        NOMBRE5.setText("Salinas Bailón Miranda Angélica ");
        jPanel1.add(NOMBRE5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 430, -1, 20));

        CONTINUAR1.setBackground(new java.awt.Color(153, 153, 153));
        CONTINUAR1.setFont(new java.awt.Font("Yu Gothic", 0, 14)); // NOI18N
        CONTINUAR1.setText("Continuar ");
        CONTINUAR1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        CONTINUAR1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CONTINUAR1ActionPerformed(evt);
            }
        });
        jPanel1.add(CONTINUAR1, new org.netbeans.lib.awtextra.AbsoluteConstraints(431, 550, 90, 30));

        FONDO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/fondo.png"))); // NOI18N
        jPanel1.add(FONDO, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, 420, 690));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 630));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CONTINUAR1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CONTINUAR1ActionPerformed
        // TODO add your handling code here:
        Menu a= new Menu();
        a.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_CONTINUAR1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Fportada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Fportada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Fportada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Fportada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Fportada().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CONTINUAR1;
    private javax.swing.JLabel EQUIPO2;
    private javax.swing.JLabel FONDO;
    private javax.swing.JLabel INTEGRANTES2;
    private javax.swing.JLabel LOGO;
    private javax.swing.JLabel LOGOUpiicsa;
    private javax.swing.JLabel NOMBRE;
    private javax.swing.JLabel NOMBRE1;
    private javax.swing.JLabel NOMBRE2;
    private javax.swing.JLabel NOMBRE3;
    private javax.swing.JLabel NOMBRE4;
    private javax.swing.JLabel NOMBRE5;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
