package GUI;
/**
 *
 * @author MASB
 */
import cajeroatm.SolicitudSaldo;
import cajeroatm.Retiro;
import cajeroatm.Deposito;
import java.util.Date;
import java.text.SimpleDateFormat;
import java.util.*;
import cajeroatm.BaseDatosBanco;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;


public class MenuPrincipaal extends javax.swing.JFrame implements Runnable{
String hora, minutos, segundos;
Thread hilo;
BaseDatosBanco baseDatosBanco = new BaseDatosBanco();
SolicitudSaldo solicituds; 
Retiro retiro;
Deposito deposito;
int cuenta;
int NIP;
double monto;
boolean tecla;
String saldo; 

/**
     * Creates new form FATM
     */
    public MenuPrincipaal(){
        initComponents(); 
        setIconImage(new ImageIcon(getClass().getResource("../IMAGENES/icono.jpeg")).getImage());
        
        USUARIONIP.setVisible(false);
        //POSISIONAMIENTO DE INTERFAZ A CENTRO  
        this.setLocationRelativeTo(null);
        
        //FECHA Y HORA ACTUALES
         Bfecha.setText(fecha());
         hilo= new Thread(this);
         hilo.start();
         setVisible(true);
         
        lbSalir.setVisible(true);
        lbRegresar.setVisible(false);
        lbSolicitudS.setVisible(false);
        lbRetiro.setVisible(false);
        lbDeposito.setVisible(false);
        lbOtro.setVisible(false);
        tfOtroM.setVisible(false);
        btAceptar.setVisible(false);
    }
    
    public void hora(){
        Calendar calendario = new GregorianCalendar();
        Date horaactual=new Date();
        calendario.setTime(horaactual);
        hora=calendario.get(Calendar.HOUR_OF_DAY)>9?""+calendario.get(Calendar.HOUR_OF_DAY):"0"+calendario.get(Calendar.HOUR_OF_DAY);
        minutos=calendario.get(Calendar.MINUTE)>9?""+calendario.get(Calendar.MINUTE):"0"+calendario.get(Calendar.MINUTE);
        segundos=calendario.get(Calendar.SECOND)>9?""+calendario.get(Calendar.SECOND):"0"+calendario.get(Calendar.SECOND);
    }
    
    public void run(){
       //while 
       Thread current=Thread.currentThread();
       while(current == hilo){
           hora();
           Bhora.setText(hora+":"+minutos+":"+segundos);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelFONDO = new javax.swing.JPanel();
        jPanelPantalla = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        LOGO = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        Bfecha = new javax.swing.JLabel();
        Fecha = new javax.swing.JLabel();
        Hora = new javax.swing.JLabel();
        Bhora = new javax.swing.JLabel();
        lbBienvenido = new javax.swing.JLabel();
        USUARIONIP = new javax.swing.JPasswordField();
        USUARIOCUENTA = new javax.swing.JTextField();
        SALIR1 = new javax.swing.JLabel();
        lbIntroduzcaDatos = new javax.swing.JLabel();
        lbSolicitudS = new javax.swing.JLabel();
        lbRetiro = new javax.swing.JLabel();
        lbDeposito = new javax.swing.JLabel();
        lbSalir = new javax.swing.JLabel();
        lbRegresar = new javax.swing.JLabel();
        lb100 = new javax.swing.JLabel();
        lbOtro = new javax.swing.JLabel();
        tfOtroM = new javax.swing.JTextField();
        btAceptar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        bt2 = new javax.swing.JButton();
        bt1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton0 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jButtonCONFIRMAR = new javax.swing.JButton();
        jButtonCANCELAR = new javax.swing.JButton();
        btBORRAR = new javax.swing.JButton();
        bt100 = new javax.swing.JButton();
        btRegresar = new javax.swing.JButton();
        btSalir = new javax.swing.JButton();
        btRetiro = new javax.swing.JButton();
        btDeposito = new javax.swing.JButton();
        btSaldo = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        RANURA = new javax.swing.JPanel();
        RANURA1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelFONDO.setBackground(new java.awt.Color(102, 102, 102));
        jPanelFONDO.setForeground(new java.awt.Color(102, 102, 102));

        jPanelPantalla.setBackground(new java.awt.Color(204, 204, 204));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        LOGO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/LOGO.png"))); // NOI18N

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        Bfecha.setText("DD/MM/AAAA");

        Fecha.setText("F E C H A : ");

        Hora.setText("H O R A : ");

        Bhora.setText("00:00:00");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Hora)
                    .addComponent(Fecha))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Bfecha)
                    .addComponent(Bhora))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Fecha)
                    .addComponent(Bfecha))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Hora)
                    .addComponent(Bhora))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lbBienvenido.setFont(new java.awt.Font("Agency FB", 1, 48)); // NOI18N
        lbBienvenido.setForeground(new java.awt.Color(153, 153, 153));
        lbBienvenido.setText("¡ B I E N V E N I D @ !");

        USUARIONIP.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        USUARIONIP.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                USUARIONIPFocusGained(evt);
            }
        });
        USUARIONIP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                USUARIONIPMouseClicked(evt);
            }
        });
        USUARIONIP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                USUARIONIPActionPerformed(evt);
            }
        });

        USUARIOCUENTA.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        USUARIOCUENTA.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                USUARIOCUENTAFocusGained(evt);
            }
        });
        USUARIOCUENTA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                USUARIOCUENTAActionPerformed(evt);
            }
        });

        SALIR1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        SALIR1.setText("USUARIO");

        lbIntroduzcaDatos.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbIntroduzcaDatos.setForeground(new java.awt.Color(102, 102, 102));
        lbIntroduzcaDatos.setText("Introduzca sus datos . . . ");

        lbSolicitudS.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbSolicitudS.setForeground(new java.awt.Color(102, 102, 102));
        lbSolicitudS.setText("SOLICITUD DE SALDO  >>");

        lbRetiro.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbRetiro.setForeground(new java.awt.Color(102, 102, 102));
        lbRetiro.setText("RETIRO  >>");

        lbDeposito.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbDeposito.setForeground(new java.awt.Color(102, 102, 102));
        lbDeposito.setText("DÉPOSITO  >>");

        lbSalir.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbSalir.setForeground(new java.awt.Color(102, 102, 102));
        lbSalir.setText("<<  SALIR");

        lbRegresar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbRegresar.setForeground(new java.awt.Color(102, 102, 102));
        lbRegresar.setText("<<  REGRESAR");

        lb100.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lb100.setForeground(new java.awt.Color(102, 102, 102));
        lb100.setText("\"");

        lbOtro.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbOtro.setText("Otro monto:");

        tfOtroM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfOtroMActionPerformed(evt);
            }
        });

        btAceptar.setBackground(new java.awt.Color(0, 102, 51));
        btAceptar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btAceptar.setForeground(new java.awt.Color(51, 51, 51));
        btAceptar.setText("ACEPTAR");
        btAceptar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btAceptarMouseClicked(evt);
            }
        });
        btAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lb100, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbRegresar)
                            .addComponent(lbSalir))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(LOGO)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(77, 77, 77)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(lbBienvenido, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addComponent(lbOtro)
                                                        .addGap(30, 30, 30)
                                                        .addComponent(tfOtroM, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(btAceptar))
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addGap(50, 50, 50)
                                                        .addComponent(lbIntroduzcaDatos))
                                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(USUARIOCUENTA, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(USUARIONIP, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 330, Short.MAX_VALUE))))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lbSolicitudS)
                                        .addGap(9, 9, 9)))
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lbDeposito)
                                    .addComponent(lbRetiro))
                                .addGap(26, 26, 26))))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(SALIR1)
                .addGap(499, 499, 499))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(LOGO)
                        .addGap(57, 57, 57)
                        .addComponent(lb100)
                        .addGap(83, 83, 83)
                        .addComponent(lbRegresar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbOtro)
                            .addComponent(tfOtroM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btAceptar))
                        .addGap(31, 31, 31))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbBienvenido, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbIntroduzcaDatos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbSolicitudS)
                        .addGap(38, 38, 38)
                        .addComponent(SALIR1)
                        .addGap(18, 18, 18)
                        .addComponent(USUARIOCUENTA, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                        .addComponent(lbRetiro)
                        .addGap(53, 53, 53)
                        .addComponent(USUARIONIP, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbDeposito)
                    .addComponent(lbSalir))
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout jPanelPantallaLayout = new javax.swing.GroupLayout(jPanelPantalla);
        jPanelPantalla.setLayout(jPanelPantallaLayout);
        jPanelPantallaLayout.setHorizontalGroup(
            jPanelPantallaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPantallaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelPantallaLayout.setVerticalGroup(
            jPanelPantallaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPantallaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        bt2.setBackground(new java.awt.Color(153, 153, 153));
        bt2.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        bt2.setText("2");
        bt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt2ActionPerformed(evt);
            }
        });

        bt1.setBackground(new java.awt.Color(153, 153, 153));
        bt1.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        bt1.setText("1");
        bt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt1ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(153, 153, 153));
        jButton3.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        jButton3.setText("3");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(153, 153, 153));
        jButton4.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        jButton4.setText("4");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(153, 153, 153));
        jButton5.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        jButton5.setText("5");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(153, 153, 153));
        jButton6.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        jButton6.setText("6");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setBackground(new java.awt.Color(153, 153, 153));
        jButton7.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        jButton7.setText("7");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setBackground(new java.awt.Color(153, 153, 153));
        jButton8.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        jButton8.setText("8");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setBackground(new java.awt.Color(153, 153, 153));
        jButton9.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        jButton9.setText("9");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton0.setBackground(new java.awt.Color(153, 153, 153));
        jButton0.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        jButton0.setText("0");
        jButton0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton0ActionPerformed(evt);
            }
        });

        jPanel8.setBackground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 9, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jButtonCONFIRMAR.setBackground(new java.awt.Color(0, 102, 0));
        jButtonCONFIRMAR.setText("CONFIRMAR");
        jButtonCONFIRMAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCONFIRMARActionPerformed(evt);
            }
        });

        jButtonCANCELAR.setBackground(new java.awt.Color(153, 0, 0));
        jButtonCANCELAR.setText("CANCELAR");
        jButtonCANCELAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCANCELARActionPerformed(evt);
            }
        });

        btBORRAR.setBackground(new java.awt.Color(255, 255, 51));
        btBORRAR.setText("BORRAR");
        btBORRAR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btBORRARMouseClicked(evt);
            }
        });
        btBORRAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBORRARActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(bt1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bt2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton0, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(38, 38, 38)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonCANCELAR, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCONFIRMAR, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btBORRAR, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jButtonCONFIRMAR, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(jButtonCANCELAR, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(btBORRAR, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(bt1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(bt2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(21, 21, 21)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(21, 21, 21)
                                .addComponent(jButton0, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        bt100.setBackground(new java.awt.Color(153, 153, 153));
        bt100.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        bt100.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt100MouseClicked(evt);
            }
        });
        bt100.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt100ActionPerformed(evt);
            }
        });

        btRegresar.setBackground(new java.awt.Color(153, 153, 153));
        btRegresar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btRegresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btRegresarMouseClicked(evt);
            }
        });
        btRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRegresarActionPerformed(evt);
            }
        });

        btSalir.setBackground(new java.awt.Color(153, 153, 153));
        btSalir.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btSalirMouseClicked(evt);
            }
        });
        btSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalirActionPerformed(evt);
            }
        });

        btRetiro.setBackground(new java.awt.Color(153, 153, 153));
        btRetiro.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btRetiro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btRetiroMouseClicked(evt);
            }
        });
        btRetiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRetiroActionPerformed(evt);
            }
        });

        btDeposito.setBackground(new java.awt.Color(153, 153, 153));
        btDeposito.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btDeposito.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btDepositoMouseClicked(evt);
            }
        });
        btDeposito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDepositoActionPerformed(evt);
            }
        });

        btSaldo.setBackground(new java.awt.Color(153, 153, 153));
        btSaldo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btSaldo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btSaldoMouseClicked(evt);
            }
        });
        btSaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSaldoActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/billete.png"))); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/Recibir billete.png"))); // NOI18N

        RANURA.setBackground(new java.awt.Color(51, 51, 51));
        RANURA.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout RANURALayout = new javax.swing.GroupLayout(RANURA);
        RANURA.setLayout(RANURALayout);
        RANURALayout.setHorizontalGroup(
            RANURALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 412, Short.MAX_VALUE)
        );
        RANURALayout.setVerticalGroup(
            RANURALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 21, Short.MAX_VALUE)
        );

        RANURA1.setBackground(new java.awt.Color(51, 51, 51));
        RANURA1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout RANURA1Layout = new javax.swing.GroupLayout(RANURA1);
        RANURA1.setLayout(RANURA1Layout);
        RANURA1Layout.setHorizontalGroup(
            RANURA1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        RANURA1Layout.setVerticalGroup(
            RANURA1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 21, Short.MAX_VALUE)
        );

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("R E T I R E   E L  E F E C T I V O");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("I N S E R T E   E L  E F E C T I V O");

        javax.swing.GroupLayout jPanelFONDOLayout = new javax.swing.GroupLayout(jPanelFONDO);
        jPanelFONDO.setLayout(jPanelFONDOLayout);
        jPanelFONDOLayout.setHorizontalGroup(
            jPanelFONDOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFONDOLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanelFONDOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btRegresar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt100, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btSalir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelFONDOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelFONDOLayout.createSequentialGroup()
                        .addComponent(jPanelPantalla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelFONDOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btRetiro, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btDeposito, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanelFONDOLayout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanelFONDOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelFONDOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(RANURA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(RANURA1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanelFONDOLayout.createSequentialGroup()
                                .addGap(103, 103, 103)
                                .addComponent(jLabel3))
                            .addGroup(jPanelFONDOLayout.createSequentialGroup()
                                .addGap(109, 109, 109)
                                .addComponent(jLabel4)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanelFONDOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(92, 92, 92))))
        );
        jPanelFONDOLayout.setVerticalGroup(
            jPanelFONDOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFONDOLayout.createSequentialGroup()
                .addGroup(jPanelFONDOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelFONDOLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jPanelPantalla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanelFONDOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelFONDOLayout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addGroup(jPanelFONDOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanelFONDOLayout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                                        .addComponent(jLabel2))
                                    .addGroup(jPanelFONDOLayout.createSequentialGroup()
                                        .addGap(22, 22, 22)
                                        .addComponent(jLabel4)
                                        .addGap(18, 18, 18)
                                        .addComponent(RANURA1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel3)
                                        .addGap(18, 18, 18)
                                        .addComponent(RANURA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanelFONDOLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanelFONDOLayout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addComponent(bt100, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelFONDOLayout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(btSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btRetiro, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btDeposito, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelFONDO, javax.swing.GroupLayout.PREFERRED_SIZE, 1312, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelFONDO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt2ActionPerformed
        // TODO add your handling code here:
       if(comprobar()){
        USUARIOCUENTA.setText(USUARIOCUENTA.getText()+"2");}
        else{
            USUARIONIP.setText(USUARIONIP.getText()+"2");
        }
             
    }//GEN-LAST:event_bt2ActionPerformed

    private void bt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt1ActionPerformed
        // TODO add your handling code here:
        if(comprobar()){
        USUARIOCUENTA.setText(USUARIOCUENTA.getText()+"1");}
        else{
            USUARIONIP.setText(USUARIONIP.getText()+"1");
        }
  
    }//GEN-LAST:event_bt1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if(comprobar()){
        USUARIOCUENTA.setText(USUARIOCUENTA.getText()+"3");}
        else{
            USUARIONIP.setText(USUARIONIP.getText()+"3");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
       if(comprobar()){
        USUARIOCUENTA.setText(USUARIOCUENTA.getText()+"4");}
        else{
            USUARIONIP.setText(USUARIONIP.getText()+"4");
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
       if(comprobar()){
        USUARIOCUENTA.setText(USUARIOCUENTA.getText()+"5");}
        else{
            USUARIONIP.setText(USUARIONIP.getText()+"5");
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
       if(comprobar()){
        USUARIOCUENTA.setText(USUARIOCUENTA.getText()+"6");}
        else{
            USUARIONIP.setText(USUARIONIP.getText()+"6");
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        if(comprobar()){
        USUARIOCUENTA.setText(USUARIOCUENTA.getText()+"7");}
        else{
            USUARIONIP.setText(USUARIONIP.getText()+"7");
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
     if(comprobar()){
        USUARIOCUENTA.setText(USUARIOCUENTA.getText()+"8");}
        else{
            USUARIONIP.setText(USUARIONIP.getText()+"8");
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        if(comprobar()){
        USUARIOCUENTA.setText(USUARIOCUENTA.getText()+"9");}
        else{
            USUARIONIP.setText(USUARIONIP.getText()+"9");
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton0ActionPerformed
        // TODO add your handling code here:
       if(comprobar()){
        USUARIOCUENTA.setText(USUARIOCUENTA.getText()+"0");}
        else{
            USUARIONIP.setText(USUARIONIP.getText()+"0");
        }
    }//GEN-LAST:event_jButton0ActionPerformed

    private void bt100ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt100ActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_bt100ActionPerformed

    private void btRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRegresarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btRegresarActionPerformed

    private void btSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btSalirActionPerformed

    private void btRetiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRetiroActionPerformed
       
    }//GEN-LAST:event_btRetiroActionPerformed

    private void btDepositoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDepositoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btDepositoActionPerformed

    private void btSaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSaldoActionPerformed
       
    }//GEN-LAST:event_btSaldoActionPerformed

    private void jButtonCANCELARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCANCELARActionPerformed
        USUARIOCUENTA.setText("");
        USUARIOCUENTA.setVisible(true);
        SALIR1.setText("USUARIO");
        USUARIONIP.setVisible(false);
        // TODO add your handling code he&re:
    }//GEN-LAST:event_jButtonCANCELARActionPerformed

    private void btBORRARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBORRARActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btBORRARActionPerformed

    private void USUARIOCUENTAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_USUARIOCUENTAActionPerformed
        
    }//GEN-LAST:event_USUARIOCUENTAActionPerformed

    private void USUARIONIPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_USUARIONIPActionPerformed
        // TODO add your handling code here:
        
        
                                     
    }//GEN-LAST:event_USUARIONIPActionPerformed

    private void USUARIONIPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_USUARIONIPMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_USUARIONIPMouseClicked

    private void btBORRARMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btBORRARMouseClicked
         if (comprobar()) {
            USUARIOCUENTA.setText("");
            USUARIOCUENTA.requestFocus();
        } else {
            USUARIONIP.setText("");
            USUARIONIP.requestFocus();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btBORRARMouseClicked

    private void USUARIONIPFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_USUARIONIPFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_USUARIONIPFocusGained

    private void USUARIOCUENTAFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_USUARIOCUENTAFocusGained
        // TODO add your handling code here:
       
    }//GEN-LAST:event_USUARIOCUENTAFocusGained

    private void jButtonCONFIRMARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCONFIRMARActionPerformed
        // TODO add your handling code here:
    if(SALIR1.getText().equals("USUARIO")){
    USUARIOCUENTA.setVisible(false);
    SALIR1.setText("NIP");
    USUARIONIP.setVisible(true);
    USUARIONIP.requestFocus();
    }
    else if(SALIR1.getText().equals("NIP")){
    cuenta=Integer.parseInt(USUARIOCUENTA.getText());
    NIP=Integer.parseInt(USUARIONIP.getText());
    USUARIOCUENTA.setText("");
    USUARIONIP.setText("");
    if(baseDatosBanco.autenticarUsuario(cuenta,NIP)){
        JOptionPane.showMessageDialog(null, "Los datos son correctos", null, JOptionPane.INFORMATION_MESSAGE);
        USUARIOCUENTA.setVisible(false);
        USUARIONIP.setVisible(false);
        SALIR1.setVisible(false);
         lbSolicitudS.setVisible(true);
         lbRetiro.setVisible(true);
         lbDeposito.setVisible(true);
         lbIntroduzcaDatos.setText("Seleccione una opción");
            //VALIDACIÓN DE BOTÓN PARA PASAR A LA INTERFAZ DE MENÚ PRINCIAPL 
           
            //setSaldo(saldo);
           // System.out.println(saldo);
           // FATM a= new FATM();
            //a.setVisible(true);
          //  this.setVisible(false);
        } else{
            //AVISO DE DATOS INVALIDO 
            JOptionPane.showMessageDialog(null, "Verifica tus datos", "Error", JOptionPane.ERROR_MESSAGE);
            USUARIONIP.setVisible(false);
            SALIR1.setText("USUARIO");
            USUARIOCUENTA.setVisible(true);
            
        }
    }
    
    }//GEN-LAST:event_jButtonCONFIRMARActionPerformed

    private void btSaldoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btSaldoMouseClicked
        SALIR1.setVisible(true);
        solicituds= new SolicitudSaldo(cuenta, baseDatosBanco);
        deposito= new Deposito(cuenta, baseDatosBanco);
        retiro= new Retiro(cuenta, baseDatosBanco);
        saldo = solicituds.consultar();
        lbSolicitudS.setVisible(false);
        lbRetiro.setVisible(false);
        lbDeposito.setVisible(false);
        lbIntroduzcaDatos.setText("Su saldo es de: ");
        /*
        lbSalir.setVisible(false);
        lbRegresar.setVisible(false);
        lbDeposito.setVisible(false);
        lbIntroduzcaDatos.setVisible(false);
        lb100.setText("<<$100");*/
        SALIR1.setText("$"+saldo);
        lbBienvenido.setText("S A L D O");
               
        if(lbSolicitudS.getText().equals("$300>>")){
        retiro.retirar(300);
        JOptionPane.showMessageDialog(null, "Retiro exitoso", null, JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btSaldoMouseClicked

    private void bt100MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt100MouseClicked
        retiro= new Retiro(cuenta, baseDatosBanco);
        deposito= new Deposito(cuenta, baseDatosBanco); 
        if(lb100.getText().equals("<<$100")){
        retiro.retirar(100);
        JOptionPane.showMessageDialog(null, "Retiro exitoso", null, JOptionPane.INFORMATION_MESSAGE);
    }
        else if(lb100.getText().equals("<< $100")){
           
        deposito.Depositar(100);
        JOptionPane.showMessageDialog(null, "Deposito exitoso", null, JOptionPane.INFORMATION_MESSAGE);
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_bt100MouseClicked

    private void btRegresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btRegresarMouseClicked

        if(lbRegresar.getText().equals("<<$200")){
        retiro= new Retiro(cuenta, baseDatosBanco);
        retiro.retirar(200);
        JOptionPane.showMessageDialog(null, "Retiro exitoso", null, JOptionPane.INFORMATION_MESSAGE);
        }
        if(lbRegresar.getText().equals("<< $200")){
        deposito= new Deposito(cuenta, baseDatosBanco);
        deposito.Depositar(200);
        JOptionPane.showMessageDialog(null, "Deposito exitoso", null, JOptionPane.INFORMATION_MESSAGE);
        }
        
        // TODO add your handling code here:
    }//GEN-LAST:event_btRegresarMouseClicked

    private void btRetiroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btRetiroMouseClicked
        lbBienvenido.setText("R E T I R O");
        lb100.setText("<<$100");
        lbRegresar.setText("<<$200");
        lbSolicitudS.setText("$300>>");
        lbOtro.setVisible(true);
        tfOtroM.setVisible(true); 
        btAceptar.setVisible(true);
        lb100.setVisible(true);
        lbRetiro.setVisible(false);
        lbRegresar.setVisible(true);
        lbSolicitudS.setVisible(true);
        
    }//GEN-LAST:event_btRetiroMouseClicked

    private void tfOtroMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfOtroMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfOtroMActionPerformed

    private void btAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAceptarActionPerformed
    retiro= new Retiro(cuenta, baseDatosBanco);
    monto= Double.parseDouble(tfOtroM.getText());
    retiro.retirar(monto);
    JOptionPane.showMessageDialog(null, "Retiro exitoso",null, JOptionPane.INFORMATION_MESSAGE);
    
    
           // TODO add your handling code here:
    }//GEN-LAST:event_btAceptarActionPerformed

    private void btAceptarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btAceptarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btAceptarMouseClicked

    private void btSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btSalirMouseClicked
        lbSolicitudS.setText("SOLICITUD DE SALDO  >>");
        lbRetiro.setText("RETIRO >>");
        lbDeposito.setText("DEPOSITO >>");
        lbBienvenido.setText("¡ B I E N V E N I D @ !");
        SALIR1.setVisible(false);
        lbOtro.setVisible(false);
        btAceptar.setVisible(false);
        tfOtroM.setVisible(false);
        lbSalir.setVisible(true);
        lb100.setVisible(false);
        lbRegresar.setVisible(false);
        lbSolicitudS.setVisible(true);
        lbRetiro.setVisible(true);
        lbDeposito.setVisible(true);
        lbIntroduzcaDatos.setVisible(false);
        SALIR1.setText("");
        
        if(SALIR1.getText().equals("USUARIO")){
        Menu menu = new Menu();
        menu.setVisible(true);
        this.setVisible(false);
        }
        else if(SALIR1.getText().equals("NIP")){
        Menu menu = new Menu();
        menu.setVisible(true);
        this.setVisible(false);
        }
    }//GEN-LAST:event_btSalirMouseClicked

    private void btDepositoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btDepositoMouseClicked
        lb100.setText("<< $100");
        lbRegresar.setText("<< $200");
        lbSolicitudS.setText("$300 >>");
        lb100.setVisible(true);
        lbRegresar.setVisible(true);
        lbSolicitudS.setVisible(true);
        lbRetiro.setVisible(false);
        lbDeposito.setVisible(false);
        lbOtro.setVisible(true);
        tfOtroM.setVisible(true); 
        btAceptar.setVisible(true);
        
        
// TODO add your handling code here:
    }//GEN-LAST:event_btDepositoMouseClicked

    public String getSaldo() {
        return saldo;
    }

    public void setSaldo(String saldo) {
        this.saldo = saldo;
    }


    /**
     * @param args the command line arguments
     */
    public static String fecha(){
        Date fecha=new Date();
        SimpleDateFormat formatofecha= new SimpleDateFormat("dd/MM/YYYY");
        return formatofecha.format(fecha);
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipaal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipaal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipaal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipaal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipaal().setVisible(true);
            }
        });
    }
    public boolean comprobar() {
        if (SALIR1.getText().equals("USUARIO")) {
            return true;
        } else {
            return false;
        }
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Bfecha;
    private javax.swing.JLabel Bhora;
    private javax.swing.JLabel Fecha;
    private javax.swing.JLabel Hora;
    private javax.swing.JLabel LOGO;
    private javax.swing.JPanel RANURA;
    private javax.swing.JPanel RANURA1;
    private javax.swing.JLabel SALIR1;
    public static javax.swing.JTextField USUARIOCUENTA;
    public static javax.swing.JPasswordField USUARIONIP;
    private javax.swing.JButton bt1;
    private javax.swing.JButton bt100;
    private javax.swing.JButton bt2;
    private javax.swing.JButton btAceptar;
    private javax.swing.JButton btBORRAR;
    private javax.swing.JButton btDeposito;
    private javax.swing.JButton btRegresar;
    private javax.swing.JButton btRetiro;
    private javax.swing.JButton btSaldo;
    private javax.swing.JButton btSalir;
    private javax.swing.JButton jButton0;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JButton jButtonCANCELAR;
    private javax.swing.JButton jButtonCONFIRMAR;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanelFONDO;
    private javax.swing.JPanel jPanelPantalla;
    private javax.swing.JLabel lb100;
    private javax.swing.JLabel lbBienvenido;
    private javax.swing.JLabel lbDeposito;
    private javax.swing.JLabel lbIntroduzcaDatos;
    private javax.swing.JLabel lbOtro;
    private javax.swing.JLabel lbRegresar;
    private javax.swing.JLabel lbRetiro;
    private javax.swing.JLabel lbSalir;
    private javax.swing.JLabel lbSolicitudS;
    private javax.swing.JTextField tfOtroM;
    // End of variables declaration//GEN-END:variables
}
